### ISSUE TITLE
Create a logo in svg and add it to the home page

### ISSUE THREAD

**Issue by stevehu** [networknt/light-doc#1]
The section in hero.html is commented out already and it needs to be enabled once the logo is done. 

I am thinking the logo should be a lighting in a cloud.

**Comment by illumise** [comment]
Hi Steve,

Gonzalo told me that you needed a logo design for the NetworkNT documentation site. 
Could you give me some guidance as to what you are looking for?
Thanks,
Marie

**Comment by stevehu** [comment]
@illumise We are working on a cloud native platform which is lighting fast and light weight. I was thinking a lightning across a cloud; however, there is no limitation with your imagination. search "lightning cloud" on google will give you a lot nature images in nature and it might be helpful. Thanks.

**Comment by illumise** [comment]
@stevehu here are some examples I was working on. I pulled some colours from the http://doc.networknt.com/ website to incorporate in but let me know if there's a specific one you like, specific colours etc. Sorry for the delay, school has been quite hectic now that is year-end.

![light-4j-01](https://user-images.githubusercontent.com/22944303/34009273-41d96b56-e0d6-11e7-863f-49696cadadbf.png)
![light-4j-02](https://user-images.githubusercontent.com/22944303/34009275-42e3e30a-e0d6-11e7-81bb-4489e5128f6a.png)

Thanks,
Marie

**Comment by stevehu** [comment]
@illumise Thanks a lot. All of them look really nice for me. If you wan me to choose the best, I would say number 3 is the best. Regarding to the colour, I have no preference as the colour schema is borrowed on doc.networknt.com from the existing template. I would say let's keep all of them and choose whichever fit in the background. Do you know how we can convert png file to ico like this file. 

https://github.com/networknt/light-doc/blob/master/static/favicon.ico

**Comment by illumise** [comment]
Hi Steve,

Hope you had a nice holiday. I have attached the icons you selected, 250px and 300px respectively. As well, you will find the favicons attached. 

Let me know if there are any problems or if you need any other sizes.

Thanks,
Marie 

[250X250.zip](https://github.com/networknt/light-doc/files/1607675/250X250.zip)
[300X300.zip](https://github.com/networknt/light-doc/files/1607676/300X300.zip)
[FAVICONS.zip](https://github.com/networknt/light-doc/files/1607677/FAVICONS.zip)

**Comment by stevehu** [comment]
@illumise Thanks a lot for the effort. I have deployed these images to the document site and they looks really good. The following link shows the favicon and the card image is still cached by the CDN so we have to wait for a while until it shows up. 

https://doc.networknt.com/
