### ISSUE TITLE
Tracking: Broken links

### ISSUE THREAD

**Issue by DSchrupert** [networknt/light-doc#19]
Tracking broken links:

### Main header: 
- Blog: https://doc.networknt.com/blog/ :ballot_box_with_check:

### Home page:
- Check out light-4j middleware handlers. : http://docs.networknt.com/ :ballot_box_with_check:
- Use the right framework for the right product. : https://www.networknt.com/templates/ :ballot_box_with_check:
- OAuth2, Portal and other infrastructure services. : https://www.networknt.com/templates/ :ballot_box_with_check:
- Tool chain for code generation, devops and CI/CD. : https://www.networknt.com/templates/ :ballot_box_with_check:

#### Left menu:
- Milestones: https://www.networknt.com/milestone/ :ballot_box_with_check:
- About:
  - Features: https://www.networknt.com/about/features/ :ballot_box_with_check:
- Contribute:
  - Development: https://www.networknt.com/contribute/development/ :ballot_box_with_check:
- Troubleshooting:
  - Mostly empty page. :ballot_box_with_check:

#### https://www.networknt.com/contribute/
 - "Read more" link under "Contribute to Hugo Development" :ballot_box_with_check:
 - "Tutorial" -> blank. :ballot_box_with_check:
 - "Example" -> blank. :ballot_box_with_check:

#### https://www.networknt.com/consumer/
  - Customized Grant -> blank. :black_square_button:
  - Token Startup -> blank. :black_square_button:
  - Long Lived Token -> blank. :black_square_button:
  - Traceability -> blank. :black_square_button:
  - Traceability Id -> blank. :black_square_button:
  - Correlation Id -> blank. :black_square_button:
  - Service Discovery -> blank. :black_square_button:
  - Registry -> blank. :black_square_button:
  - Standalone Registry -> blank. :black_square_button:
  - Docker Registry -> blank. :black_square_button:
  - Kubernetes Registry -> blank. :black_square_button:
  - Discovery -> blank. :black_square_button:
  - Consul Discovery -> blank. :black_square_button:
  - Zookeeper Discovery -> blank. :black_square_button:
  - Load Balance -> blank. :black_square_button:
  - Round Robin -> blank. :black_square_button:
  - Local First -> blank. :black_square_button:
  - Consistent Hash -> blank. :black_square_button:
  - Light Router -> blank. :black_square_button:
  - Router Use Case -> blank. :black_square_button:
  - Router Location -> blank. :black_square_button:

#### https://www.networknt.com/tool/
  - "Light Codegen" -> https://www.networknt.com/consumer/service-discovery/ :black_square_button:
  - "Why Another Generator" -> https://www.networknt.com/consumer/registry/ :black_square_button:
  - "OpenAPI Parser" -> https://www.networknt.com/consumer/load-balance/ :black_square_button:
  - "Why This Parser" -> https://www.networknt.com/consumer/round-robin/ :black_square_button:
  - "Swagger Bundler" -> https://www.networknt.com/consumer/light-router/ :black_square_button:
  - "Why Build It" -> https://www.networknt.com/consumer/router-use-case/ :black_square_button:
  
#### https://www.networknt.com/tool/openapi-converter/
  - "openapi-parser" -> blank :ballot_box_with_check:
  - "light-codegen response from example." -> https://www.networknt.com/tutorial/generator/openapi-mock/ (Yes. Correct.) :ballot_box_with_check:

**Comment by stevehu** [comment]
The following is used to trace what has been fixed. 
* Blog has been commented out from the main header.
* The link for features in about has been fixed.

**Comment by NicholasAzar** [comment]
@stevehu if you have access to edit my comment, you can feel free to replace the : black_square_button : with : ballot_box_with_check : when fixed

**Comment by stevehu** [comment]
@NicholasAzar I am learning new skills every day. This is fantastic for tracking things. Thanks a lot.
