### ISSUE TITLE
design a card image which is associated with the site. 

### ISSUE THREAD

**Issue by stevehu** [networknt/light-doc#2]
For example, the hugo site card is 

https://github.com/networknt/light-doc/blob/master/themes/gohugoioTheme/static/images/gohugoio-card.png

**Comment by NicholasAzar** [comment]
@stevehu was this fixed in https://github.com/networknt/light-doc/commit/7039e12c3d7370babcb4bb86383cc7d0b6819644?

Would you like to use the same logo in gitter?

**Comment by stevehu** [comment]
It looks like fixed already but not this png file. Currently, the it is using the logo in slack post. As for gitter, I think we will need to wait until the logo is stable. I am still thinking to change the colour schema a little bit to make the lightning orange colour to have bigger contract with the backgroud. However, it needs to be tested out to see if it looks good.

**Comment by stevehu** [comment]
For now, let's keep what we have until there is a better idea.
