### ISSUE TITLE
add doc for circuit breaker

### ISSUE THREAD

**Issue by stevehu** [networknt/light-doc#75]
As there are too many items in the client module, let's add new features to the consumer section. 

https://github.com/networknt/light-doc/blob/master/content/en/consumer/circuit-breaker.md

**Comment by jefperito** [comment]
no problem! i`ll need some review with English grammar because i am not fully English speaker.

**Comment by stevehu** [comment]
@jefperito Don't worry about the grammar. I am not a native English speaker neither so I have to rely on some tools to check the typos and grammar ;) I can help to review as long as the raw material is available. Thanks.
