### ISSUE TITLE
Links for /tutorial/common/ are provided in different order than next/prev links

### ISSUE THREAD

**Issue by retinaburn** [networknt/light-doc#9]
On navigating to https://doc.networknt.com/tutorial/common/ the links are provide as Unit test, Integration test, Consumer driven contract test, End-to-end test.

If you click on Unit Test, then it actually navigates you to the last of the four items.

I believe the expectation is that the next/previous links would take you through the links in the order listed.  Not sure how to fix in Hugo.

**Comment by stevehu** [comment]
@retinaburn Thanks for bringing this up. I am new to the Hugo and thought it would be related to the weight parameter in the header but it is not. Let's keep this issue open until we resolve it. There are a lot other places with similar issues.

**Comment by retinaburn** [comment]
Me too :) I'll take a look and see if I can resolve.

**Comment by stevehu** [comment]
Here is my update on the weight and it doesn't work :(

https://github.com/networknt/light-doc/commit/b0ca299bccdbdc8ec1f9069fd02bf91b9312229a

**Comment by NicholasAzar** [comment]
Am i misunderstanding the problem or is this already fixed? The next/prev seems to work in order of the items listed in the common page for the test links.
Although i can see the issue with the debug list of links, which makes me think @stevehu actually did fix it..

**Comment by stevehu** [comment]
The set the weight in the header helps most of the cases but it is not 100% reliable. I just don't have time to go through all of them to fix in one shot. Will get them fixed once each index is worked on. Thanks.
